- src/SvgIcon.js
Иногда из CSS полезно узнать ширину и высоту иконки, так как не все иконки квадратные
> SvgIcon: added css classes for width and height

- scripts/utils/icons.js
P.S. было бы здорово передавать путь к иконкам параметром
> Fix iconPath.match for Windows

- src/SvgIcon.tsx
fixes #107:
- добавила проп `Component` (дефолт — `div`)
- заревертила замену `div` на `span` и проброс захардкоженного `display: block;`
> feature: Component prop

- package.json
- scripts/utils/symbol.js
- src/SvgIcon.tsx
- yarn.lock
Делаем компонент иконки хоком  = –11% бандла иконок (min + gz)
> enhancement: Share icon helpers to reduce bundle size

- src/SvgIcon.tsx
```jsx
<Icon12Add aria-label="Добавить"/>
```
> fix(a11y): aria-label and aria-hidden for svg

- packages/icons-scripts/scripts/reactify.js
- packages/icons-scripts/src/SvgIcon.tsx
> fix(types): remove HTMLAttributes

- .github/workflows/pull_request.yml
- .prettierignore
- package.json
> ci: add check prettier

- .github/workflows/publish_icons.yml
- .github/workflows/publish_scripts.yml
- поправила коммит с номером версии пакета
- добавила тег к паблишу пакетов
> ci: Фиксим публикацию пакетов

- .github/workflows/npm_deprecate_package.yml
см. https://github.com/VKCOM/.github/pull/4
---
- caused by #330
> fix(GitHub Actions): mv `secrets` field for provide to token to `npm_deprecate_package`

- packages/icons-scripts/scripts/icons.js
Запускаем tsc только один раз (ускорение на 5 секунд на M1)
> fix: tsc run once

- yarn.lock
> build(deps-dev): bump json5 from 2.1.3 to 2.2.3

- packages/icons-sprite/LICENSE
- packages/icons-sprite/Readme.md
- packages/icons-sprite/package.json
- packages/icons-sprite/package.swcrc
- packages/icons-sprite/src/IconSettings.tsx
- packages/icons-sprite/src/SvgIcon.tsx
- packages/icons-sprite/src/index.ts
- packages/icons-sprite/src/sprite.ts
- packages/icons-sprite/src/warnOnce.ts
- packages/icons-sprite/tsconfig.json
- packages/icons-sprite/yarn.lock
Вынес все из icons-scripts в icons-sprite
> feat(icons-sprite): add makeIcon

- .github/workflows/publish_sprite.yml
- .github/workflows/pull_request_sprite.yml
- packages/icons-sprite/package.json
- packages/icons-sprite/yarn.lock
Упустил @types/react, добавил тестов в ci
> fix(icons-sprite): add @types/react

- .github/workflows/publish_icons.yml
- .github/workflows/publish_scripts.yml
- .github/workflows/pull_request.yml
> ci: use node 18

- packages/icons-sprite/package.json
- packages/icons-sprite/yarn.lock
Обновление @swc/helpers до 0.5
> feat(icons-sprite): update @swc/helpers to 0.5

- .github/workflows/publish_icons.yml
- .github/workflows/publish_scripts.yml
- .github/workflows/publish_sprite.yml
Забыл добавить
```yml
permissions:
id-token: write
```
> ci(publish): add permissions id-token write

- packages/icons/src/docs/docs.js
Копируем только имя, так как это удобнее чем импорт
> feat: copy only name

- yarn.lock
Обновляем зависимость, избавляемся от пакета ip
- see GHSA-78xj-cgh5-2h22
> build(node-gyp): update to 10.0.1

- packages/icons-scripts/scripts/output/react.js
Директива была написана неверно
- Fixes #696
> fix: use client

- yarn.lock
Применил
```sh
yarn dedupe
```
> chore: Deduplicate dependencies on master

- packages/icons-scripts/scripts/icons.js
> feat(scripts): add provider reexport from root entry

- yarn.lock
> build(deps-dev): update yarn.lock

- packages/icons-sprite/src/SvgIcon.tsx
- packages/icons-sprite/src/raster/components/IconAppearanceProvider/IconAppearanceProvider.ts
- packages/icons-sprite/src/raster/components/RasterIcon/RasterIcon.tsx
Добавляем use client
Бонус: `* as React` для тришейкинга
> fix(icons-sprite): use client

- packages/icons-sprite/package.json
Забыл убрать cjs и добавить `"type": "module"`
> fix(icons-sprite): rm cjs

- packages/icons-scripts/Readme.md
- packages/icons-sprite/package.json
- packages/icons-sprite/src/raster/components/RasterIcon/RasterIcon.tsx
- packages/icons/package.json
- packages/icons/scripts/webpack.config-docs.js
- packages/icons/src/docs/docs.js
- yarn.lock
Добавляем в peerDependencies  19 версию реакта
Обновляем дев зависимости внутри
> feat: support react 19

- .github/workflows/pull_request.yml
> ci: add spell-checker-filename

- .github/dependabot.yml
- .npmignore
- packages/icons/package.json
- packages/icons/scripts/docs.js
- packages/icons/scripts/rspack.config-docs.js
- packages/icons/src/docs/docs.html
- yarn.lock
Ускоряем сборку документации с 60~ секунд до 10~
> docs: use rspack

- packages/icons/package.json
> feat: add svg exports

- packages/icons-scripts/scripts/raster/icons.js
Используем path.resolve вместо require.resolve
> fix(icons-scripts): use path.resolve

- packages/icons/package.json
Добавляем в экспорт `package.json`
> feat: add package.json export

- yarn.lock
Запустил
```sh
yarn dedupe
```
> chore: deduplicate dependencies

- packages/icons-scripts/scripts/icons-map.js
- packages/icons-scripts/scripts/output/react.js
В иконках могут содержаться id которые могут повторяться при расположении на странице нескольких иконок. Первая иконка может влиять на остальные(например при display none)
Добавляем useId для иконок которым необходимы id
> fix(icons-scripts): add reactId

- packages/icons-scripts/scripts/output/react.js
Реакт выбивает ошибку если viewBox="undefined"
> fix(icons-scripts): viewBox undefined

- yarn.lock
> build(deps-dev): Bump compression to 1.8.1

- .github/workflows/pr_close.yml
Нужно добавить вызов экшена автообновления релиз ноутов.  [PR с реализаций скрипта](https://github.com/VKCOM/gh-actions/pull/683)
> tech: add call auto-update-release-notes action on close pr
