- scripts/icons.js
- src/IconSettings.tsx
- src/SvgIcon.tsx
В компанию к префиксам на классы https://github.com/VKCOM/VKUI/pull/1380
Добавляет `<IconSettings>`, в котором можно настроить:
- `classPrefix="vkui"` -> `class="vkuiIcon vkuiIcon--size-16"`
- `globalClasses` -> `class="vkuiIcon Icon vkuiIcon--size-16 Icon--size-16"`, режим обратной совместимости
> feat: Добавить префиксы на className

- src/SvgIcon.tsx
- Заменила `<div/>` на `<span/>` для блока-обертки, чтобы в кнопках была валидная верстка;
- Добавила в стили `display: block;`, дала возможность его переписать пропсами (мало ли нужно будет).
> SvgIcon: change div to span

- package.json
Сборки будут ломаться, т.к. раннеры переходят на [Yarn 1.22.19](https://github.com/actions/virtual-environments/blob/ubuntu20/20220614.0/images/linux/Ubuntu2004-Readme.md#:~:text=Yarn%201.22.19)
> ci: yarn engine version use caret ranges

- packages/icons-scripts/scripts/reactify.js
- packages/icons-scripts/src/SvgIcon.tsx
- resolves #133 
Заодно поправила нюанс с доступностью: кажется, что `aria-hidden` все же лучше `role="presentation"` для наших целей, т.к. иконки в большинстве случаев нужно в принципе скрывать от скринридера. Перебить при необходимости легко, передав свой `aria-hidden`.
> [BREAKING CHANGES] Убираем корневой div из иконок

- packages/icons-scripts/scripts/reactify.js
- packages/icons-scripts/src/SvgIcon.tsx
- добавила `title`,
- вытащила и улучшила полезную штуку от @SevereCloud из #306 (https://github.com/VKCOM/icons/pull/306/commits/b98094e3ab63fd9003827ad3b5831eafbfdf1915): оставила дефолтные стили, но даю их перебить при необходимости
> fix(icons, icons-scripts): update types; make it possible to override default `style` tag

- .github/workflows/npm_deprecate_package.yml
Используем https://github.com/VKCOM/.github/blob/main/.github/workflows/npm_deprecate_package.yml для депрекейта пакетов в NPM
---
- related to https://github.com/VKCOM/.github/issues/1
- [GitHub • Reusing workflows
](https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow)
> feat(GitHub Actions):  переиспользует `npm_deprecate_package` воркфлоу

- .github/workflows/npm_deprecate_package.yml
> етить его колотить этот копипаст 🤦‍♂️
из-за копипаста, вызов воркфлоу в `steps` попал, что невалидно
_https://github.com/VKCOM/icons/actions/runs/3996096116_
---
- caused by #330
> fix(GitHub Actions): remove steps field in `npm_deprecate_package` workflow

- .github/workflows/pull_request.yml
По умолчанию у Dependabot права только на чтение, из-за чего падает джоба `peter-evans/create-or-update-comment`
**Рис. 1** https://github.com/VKCOM/icons/actions/runs/4186867441/jobs/7255975802
В этом issue https://github.com/peter-evans/create-or-update-comment/issues/103#issuecomment-1041057863 подсказывают, что надо для Dependabot надо дать права на запись
> ci(pull_request.yml): fix dependabot permissions

- package.json
- packages/icons-sprite/package.json
- packages/icons-sprite/yarn.lock
- yarn.lock
Обновление до 5 typescript. Не виляет на .d.ts файлы.
Ускорилось время сборки типов с ~5.7 сек. до ~4.5 сек.
> bump(dev-deps): typescript 5

- packages/icons-scripts/scripts/icons-map.js
- packages/icons-scripts/scripts/icons.js
Пока тестировал пакет `@vkontakte/icons-scripts` после переезда в монорепу, нашел багу.
`@vkontakte/icons-scripts` используется в проекте, структура которого, имеет кроме папок  с размерами 
`/src/svg/20/*,` `/src/svg/40`, ещё и уникальные имена папок с иконками типа `/src/svg/Unsorted/`.
Одинковые иконки, разного размера, в такой папке могут иметь имена типа, 
```sh
/src/svg/Unsorted/live_badge_14.svg
/src/svg/Unsorted/live_badge_18.svg
```
> Мы собираем иконки из этой папки (`/src/svg/Unsorted/`) потому что `generateIcons()` принимает опцию `extraCategories`, которая по умолчанию имеет значение `["Unsorted"].
https://github.com/VKCOM/icons/blob/f8ba56cd00cca9db87579440417d9ed50c4880b1/packages/icons-scripts/scripts/options.js#L31
Текущая версия `@vkontakte/icons-scripts` упадет при …
> Fix extra category icons with similar file name prefix and different size

- .github/workflows/publish_icons.yml
Follow up: https://github.com/VKCOM/icons/pull/588
Похоже что экшен, отвечающий за публикацию документации для иконок смотрит в рутовую папку репозитория, не в воркспейс.
Моя ошибка, с чего-то взял, что раз `workingDirectory` для workflow задан для всех шагов, то и экшены используемые внутри будут отталкиватья от `workingDirectory`.
> Fix path to docs build results for github-pages-deploy action

- .github/dependabot.yml
- [Configuration options for the dependabot.yml file • groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
> dependabot: use groups; set all schedule to weekly

- packages/icons-scripts/package.json
- packages/icons-sprite/package.json
- packages/icons/package.json
Добавляем подпись от ci для npm пакетов
- [блог](https://github.blog/2023-04-19-introducing-npm-package-provenance/)
- [документация](https://docs.npmjs.com/generating-provenance-statements)
На пакетах появится подпись от GitHub Actions с ссылкой на коммит, процесс ci и т.д.
> feat: add provenance

- .github/workflows/pull_request.yml
- package.json
- packages/icons/package.json
Обновляем версию size-limit-action, чтобы можно было использовать свойство `package_manager` и избавиться от лишних скриптов.
Теперь вызываем size-limit-action напрямую из воркспейса `packages/icons`
> Bump andresz1/size-limit-action from 1.7.0 to 1.8.0

- .gitignore
- packages/icons-scripts/Readme.md
- packages/icons-scripts/scripts/icons.js
- packages/icons-scripts/scripts/options.js
- packages/icons/.npmignore
- packages/icons/package.json
- packages/icons/src/docs/docs.js
Сейчас ES6 билд генерит файлы по вложенности на уровень ниже, но в ts файлах, которые сгенерированы для ассетов, у нас уже стоит путь чувствительный к изменению вложенности.
Теперь файлы для es6 генерятся в отдельной папке на уровне с билдом es5, причины выноса в отдельную папку:
1. Была идея класть es6 файлы рядом c es5 но с расширением mjs:
```
icon/test.js
icon/test.mjs
index.js
index.mjs
```
Но тогда при таком подходе контент js файлов должен иметь js расширения в импортах, mjs также - relative путь без расширения не подходит, потому что webpack например не понимает как такой кейс резолвить и выбрасывает ошибку. Отдельно собрать через tsc, либо swc код с проставленным расширением сейчас нельзя. 
2. Вынести es5 в dist/cjs, es6 в dist/es6 - в этом нет смысла, потому что все файлы должны …
> fix(icons-scripts): generate es6 output in same level with es5

- packages/icons-scripts/scripts/icons-map.js
- packages/icons-scripts/scripts/icons.js
- packages/icons-scripts/scripts/raster/icons-map.js
- packages/icons-scripts/scripts/tsc.js
- fixes #920
---
Библиотека glob после обновления перестала принимать пути в windows формате. Также в командной строке windows не работают glob паттерны, поэтому tsc не срабатывает
- Используем для библиотеки glob пути в posix формате
- Используем typescript api вместо запуска tsc
> fix(icons-scripts): glob on windows

- packages/icons/scripts/webpack.config-docs.js
- packages/icons/src/docs/docs.js
Добавил пару небольших оптимизаций для страницы документации:
1. Для компонента ползунка изменения цвета иконок (Hue) заюзал handler onChange, потому что использовавшийся до этого onChangeComplete имеет debounce 100ms, что негативно сказывалось на скорости работы ползунка.
2. В конфиге webpack, для страницы документации, убрал проп mode=development, что бы на странице использовалась production версия react.
> Little optimization for docs page

- packages/icons-scripts/scripts/icons-map.js
- packages/icons-scripts/scripts/icons.js
- packages/icons-scripts/scripts/output/react.js
- packages/icons-sprite/src/SvgIcon.tsx
Пробрасываем нужные атрибуты для корректного отображения иконки с symbol-элемента на svg элемент, который ссылается на symbol. 
closes #949
> fix: provide symbol attributes to svg root container

- packages/icons-sprite/src/SvgIcon.tsx
- closed #943
---
Свойствами `viewBox` и `id` нельзя управлять, хотя он есть в типах. Вместо того чтобы убирать из типов, даем возможность изменять `viewBox` и выставлять `id`
> fix(icons-sprite): id & viewBox

- yarn.lock
> fix(dev-deps): dedupe

- packages/icons-scripts/scripts/output/react.js
- caused by #1039
---
Иконки можно было красить с помощью атрибута `fill`. Возвращаем эту возможность
> fix(icons-scripts): fill to style color

- packages/icons/package.json
- yarn.lock
Используем каретку вместо [лока версии](https://yarnpkg.com/features/workspaces#cross-references)
```diff
- "@vkontakte/icons-scripts": "3.0.0",
+ "@vkontakte/icons-scripts": "^3.0.0",
```
> fix(icons): use caret version

- .github/workflows/publish_icons.yml
В начале publish_icons.yml установлен working_directory: packages/icons.  Из-за этого на шаге `Prepare payload data` папка  publish_workflow_payload создается в packages/icons. А на шаге `Upload payload...` папка ищется в корне.
> fix: fix upload artifacts step by set root working directory
